# Acá no hace falta una clase, basta implementar
# las funciones en el módulo e importarlo

def generarTiempoArriboA:
	# ...

def generarTiempoArriboB:
	# ...

def generarTiempoDesvioAB:
	# ...

def generarTiempoTipo1A:
	# ...

def generatTiempoTipo2A:
	# ...

def generarTiempoTipo1B:
	# ...

def generatTiempoTipo2B:
	# ...